# Generated by Django 2.2.4 on 2019-09-19 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_datetime',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 9, 20)),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 9, 20)),
        ),
    ]
