# Generated by Django 2.2.4 on 2020-03-04 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20200304_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 3, 4)),
        ),
    ]
