# Generated by Django 2.2.4 on 2019-09-19 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190920_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 16, 42, 22, 89524, tzinfo=utc)),
        ),
    ]
